# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform
on:
  push:
    branches: [ "cl_realization" ]
  pull_request:
    branches: [ "cl_realization" ]
    
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opencl-impl: [pocl, intel-cpu]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install google-test, also install g++
      run: sudo apt-get install libgtest-dev googletest google-mock libboost-dev g++

    - name: Install dependencies
      run: |
        sudo apt-get update
        case "${{ matrix.opencl-impl }}" in
          pocl)
            sudo apt-get install -y pocl-opencl-icd ocl-icd-opencl-dev
            ;;
          intel-cpu)
            sudo apt-get install -y intel-opencl-icd ocl-icd-opencl-dev
            ;;
        esac

    - name: CMake release config and build
      run: cmake -S . -B build -DWITH_TESTS=1 -DCMAKE_BUILD_TYPE=Release; cmake --build build
    
    - name: CMake release test
      run: ctest --test-dir build
    
    - name: CMake debug config and build
      run: cmake -S . -B debug -DWITH_TESTS=1 -DCMAKE_BUILD_TYPE=Debug; cmake --build debug

    - name: CMake debug test
      run: ctest --test-dir debug